% Function to write a LaTeX table for both Lee and Kuan filter results

function WriteQualityMetricsTable(P, snr_values_lee, snr_values_kuan, rmse_values_lee, rmse_values_kuan, ...
                                  psnr_values_lee, psnr_values_kuan, md_values_lee, md_values_kuan, ...
                                  ad_values_lee, ad_values_kuan, nk_values_lee, nk_values_kuan, ...
                                  nae_values_lee, nae_values_kuan, uqi_values_lee, uqi_values_kuan, ...
                                  sc_values_lee, sc_values_kuan, mssim_values_lee, mssim_values_kuan)
    
    % Prepare headers and data for the table
    H = {'M Value', 'SNR Lee (dB)', 'SNR Kuan (dB)', 'RMSE Lee', 'RMSE Kuan', ...
         'PSNR Lee (dB)', 'PSNR Kuan (dB)', 'MD Lee', 'MD Kuan', ...
         'AD Lee', 'AD Kuan', 'NK Lee', 'NK Kuan', ...
         'NAE Lee', 'NAE Kuan', 'UQI Lee', 'UQI Kuan', ...
         'SC Lee', 'SC Kuan', 'MSSIM Lee', 'MSSIM Kuan'};  % Table header
    
    % Initialize cell array for table rows
    A = cell(length(P.Lee.M_values), 1);  
    
    for ii = 1:length(P.Lee.M_values)
        A{ii} = {num2str(P.Lee.M_values(ii)), ...
                 sprintf('%.3g', mean(snr_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(snr_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(rmse_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(rmse_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(psnr_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(psnr_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(md_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(md_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(ad_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(ad_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(nk_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(nk_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(nae_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(nae_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(uqi_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(uqi_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(sc_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(sc_values_kuan(ii,:))), ...
                 sprintf('%.3g', mean(mssim_values_lee(ii,:))), ...
                 sprintf('%.3g', mean(mssim_values_kuan(ii,:)))};  % Fill each row with all metrics
    end
    
    % Define the output file
    output_filename = 'QualityMetricsTable.tex';
    output_dir = 'SavedFigures';  % Directory to save the .tex file
    if ~exist(output_dir, 'dir')
        mkdir(output_dir);
    end
    output_filepath = fullfile(output_dir, output_filename);

    % Open the file for writing
    fid = fopen(output_filepath, 'w');

    % Check if the file opened successfully
    if fid == -1
        error('Cannot open file for writing: %s', output_filepath);
    end

    % Define table format: 'c' for center, 'r' for right-aligned; '|' adds vertical lines
    FORMATtable = '|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|c|';

    % Write the table using the function
    WriteTable(fid, A, FORMATtable, H, 'Average Quality Metrics for Lee and Kuan Filters', '\small');

    % Close the file
    fclose(fid);

    % Display a message to the user
    fprintf('LaTeX table for quality metrics for both filters has been saved to %s.\n', output_filepath);
end

